CREATE TABLE `ITEM` (
	`ID`	INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE,
	`USER_ID`	TEXT,
	`NAME`	CHAR ( 50 ) NOT NULL,
	`DESCRIPTION`	TEXT NOT NULL,
	`LOCATION`	CHAR ( 50 ) NOT NULL,
	`CONTACT`	CHAR ( 100 ) NOT NULL,
	`FOUND_DATE`	DATE,
	`ADD_DATE`	TIMESTAMP NOT NULL,
	`THUMBNAIL`	CHAR ( 250 ),
	`IS_RETURNED`	BOOLEAN NOT NULL,
	`PHOTO`	TEXT
);