CREATE TABLE ITEM(
   ID SERIAL PRIMARY KEY,
   USER_ID        TEXT,
   NAME           CHAR(50)  NOT NULL,
   DESCRIPTION    TEXT      NOT NULL,
   LOCATION       CHAR(50)  NOT NULL,
   CONTACT        CHAR(100) NOT NULL,
   FOUND_DATE     DATE      NOT NULL,
   ADD_DATE       TIMESTAMP NOT NULL,
   THUMBNAIL      CHAR(250),
   IS_RETURNED    BOOLEAN   NOT NULL
)

